// AUTH

export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN = 'LOGIN';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP = 'SIGNUP';

export const INIT_REGISTER = 'INIT_REGISTER';
export const REGISTER = 'REGISTER';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT = 'LOGOUT';

export const INIT_AUTHENTICATE = 'INIT_AUTHENTICATE';
export const AUTHENTICATE = 'AUTHENTICATE';

export const INIT_FORGOT_PASSWORD = 'INIT_FORGOT_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const START_AUTH = 'START_AUTH';
export const AUTH_FAIL = 'AUTH_FAIL';

//HDJ
export const INIT_ADD_TO_GROUP = 'INIT_ADD_TO_GROUP';
export const START_ADD_TO_GROUP = 'START_ADD_TO_GROUP';
export const ADD_TO_GROUP = 'ADD_TO_GROUP';
export const ADD_TO_GROUP_FAIL = 'ADD_TO_GROUP_FAIL';

export const INIT_GET_MIXES = 'INIT_GET_MIXES';
export const START_GET_MIXES = 'START_GET_MIXES';
export const GET_MIXES = 'GET_MIXES';
export const GET_MIXES_FAIL = 'GET_MIXES_FAIL';

//PROFILE
export const INIT_GET_PROFILE_URL = 'INIT_GET_PROFILE_URL';
export const START_GET_PROFILE_URL = 'START_GET_PROFILE_URL';
export const GET_PROFILE_URL = 'GET_PROFILE_URL';
export const GET_PROFILE_URL_FAIL = 'GET_PROFILE_URL_FAIL';

export const INIT_GET_PROFILE = 'INIT_GET_PROFILE';
export const START_GET_PROFILE = 'START_GET_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

//RESET PASSWORD
export const INIT_RESET_PASSWORD = 'INIT_RESET_PASSWORD';
export const START_RESET_PASSWORD = 'START_RESET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

//MAKE A MIX
export const INIT_GET_TRACKS_AND_PLAYLISTS = 'INIT_GET_TRACKS_AND_PLAYLISTS';
export const START_GET_TRACKS_AND_PLAYLISTS = 'START_GET_TRACKS_AND_PLAYLISTS';
export const GET_TRACKS_AND_PLAYLISTS = 'GET_TRACKS_AND_PLAYLISTS';
export const GET_TRACKS_AND_PLAYLISTS_FAIL = 'GET_TRACKS_AND_PLAYLISTS_FAIL';

export const ADD_TRACK_TO_MIX = 'ADD_TRACK_TO_MIX';
export const ADD_PLAYLIST_TO_MIX = 'ADD_PLAYLIST_TO_MIX';
export const REMOVE_TRACK_FROM_MIX = 'REMOVE_TRACK_FROM_MIX';
export const REMOVE_PLAYLIST_FROM_MIX = 'REMOVE_PLAYLIST_FROM_MIX';

export const INIT_CREATE_MIX = 'INIT_CREATE_MIX';
export const START_CREATE_MIX = 'START_CREATE_MIX';
export const CREATE_MIX = 'CREATE_MIX';
export const CREATE_MIX_FAIL = 'CREATE_MIX_FAIL';

export const INIT_REMOVE_MIX = 'INIT_REMOVE_MIX';
export const START_REMOVE_MIX = 'START_REMOVE_MIX';
export const REMOVE_MIX = 'REMOVE_MIX';
export const REMOVE_MIX_FAIL = 'REMOVE_MIX_FAIL';

export const INIT_ADD_TRACKS_TO_MIX = 'INIT_ADD_TRACKS_TO_MIX';
export const START_ADD_TRACKS_TO_MIX = 'START_ADD_TRACKS_TO_MIX';
export const ADD_TRACKS_TO_MIX = 'ADD_TRACKS_TO_MIX';
export const ADD_TRACKS_TO_MIX_FAIL = 'ADD_TRACKS_TO_MIX_FAIL';

//RANKING
export const INIT_GET_RANKING_TRACKS = 'INIT_GET_RANKING_TRACKS';
export const START_GET_RANKING_TRACKS = 'START_GET_RANKING_TRACKS';
export const GET_RANKING_TRACKS = 'GET_RANKING_TRACKS';
export const GET_RANKING_TRACKS_FAIL = 'GET_RANKING_TRACKS_FAIL';

export const INIT_GET_RANKING = 'INIT_GET_RANKING';
export const START_GET_RANKING = 'START_GET_RANKING';
export const GET_RANKING = 'GET_RANKING';
export const GET_RANKING_FAIL = 'GET_RANKING_FAIL';

export const INIT_GET_CURRENT_TRACK = 'INIT_GET_CURRENT_TRACK';
export const START_GET_CURRENT_TRACK = 'START_GET_CURRENT_TRACK';
export const GET_CURRENT_TRACK = 'GET_CURRENT_TRACK';
export const GET_CURRENT_TRACK_FAIL = 'GET_CURRENT_TRACK_FAIL';

export const INIT_GET_NEXT_TRACK = 'INIT_GET_NEXT_TRACK';
export const START_GET_NEXT_TRACK = 'START_GET_NEXT_TRACK';
export const GET_NEXT_TRACK = 'GET_NEXT_TRACK';
export const GET_NEXT_TRACK_FAIL = 'GET_NEXT_TRACK_FAIL';

export const INIT_GET_PLAYING_TRACK = 'INIT_GET_PLAYING_TRACK';
export const START_GET_PLAYING_TRACK = 'START_GET_PLAYING_TRACK';
export const GET_PLAYING_TRACK = 'GET_PLAYING_TRACK';
export const GET_PLAYING_TRACK_FAIL = 'GET_PLAYING_TRACK_FAIL';

export const INIT_GET_VOTING_TRACK = 'INIT_GET_VOTING_TRACK';
export const START_GET_VOTING_TRACK = 'START_GET_VOTING_TRACK';
export const GET_VOTING_TRACK = 'GET_VOTING_TRACK';
export const GET_VOTING_TRACK_FAIL = 'GET_VOTING_TRACK_FAIL';
