// AUTH

export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN = 'LOGIN';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP = 'SIGNUP';

export const INIT_REGISTER = 'INIT_REGISTER';
export const REGISTER = 'REGISTER';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT = 'LOGOUT';

export const INIT_AUTHENTICATE = 'INIT_AUTHENTICATE';
export const AUTHENTICATE = 'AUTHENTICATE';

export const INIT_FORGOT_PASSWORD = 'INIT_FORGOT_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const START_AUTH = 'START_AUTH';
export const AUTH_FAIL = 'AUTH_FAIL';

//HDJ
export const INIT_ADD_TO_GROUP = 'INIT_ADD_TO_GROUP';
export const START_ADD_TO_GROUP = 'START_ADD_TO_GROUP';
export const ADD_TO_GROUP = 'ADD_TO_GROUP';
export const ADD_TO_GROUP_FAIL = 'ADD_TO_GROUP_FAIL';

export const INIT_GET_MIXES = 'INIT_GET_MIXES';
export const START_GET_MIXES = 'START_GET_MIXES';
export const GET_MIXES = 'GET_MIXES';
export const GET_MIXES_FAIL = 'GET_MIXES_FAIL';

//PROFILE
export const INIT_GET_PROFILE_URL = 'INIT_GET_PROFILE_URL';
export const START_GET_PROFILE_URL = 'START_GET_PROFILE_URL';
export const GET_PROFILE_URL = 'GET_PROFILE_URL';
export const GET_PROFILE_URL_FAIL = 'GET_PROFILE_URL_FAIL';

export const INIT_GET_PROFILE = 'INIT_GET_PROFILE';
export const START_GET_PROFILE = 'START_GET_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

//RESET PASSWORD
export const INIT_RESET_PASSWORD = 'INIT_RESET_PASSWORD';
export const START_RESET_PASSWORD = 'START_RESET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
